src/accounts/urls.py
from django.urls import re_path as url

from .views import (
    login_view,
    register_view,
    logout_view
)

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
]

src/bankingsystem/urls.py
from django.conf import settings
from django.urls import re_path as url, include
from django.conf.urls.static import static
from django.contrib import admin

from core.views import home, about


urlpatterns = [
    # admin
    url(r'^admin/', admin.site.urls),
    # Accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    # transactions
    url(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

src/transactions/urls.py
from django.urls import re_path as url, include

from .views import deposit_view, withdrawal_view


app_name = 'transactions'

urlpatterns = [
    # url(r'^$', home_view, name='home'),
    url(r'^deposit/$', deposit_view, name='deposit'),
    url(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
]

src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager

# TODO: Complete custom User model.
# The username field must be unique, and should include help text, validators, and error messages as appropriate.
# The email field and contact_no (phone number) field should be unique.
# Other portions of the application expect the following properties to be set:
# - account_no, returns the User's account number, if they have an account.
# - full_name, returns the User's full name, formatted as "first_name last_name".
# - balance, returns the User's account balance, if they have an account.
# - full_address, returns the User's full address, formatted as "street_address, city, state postal_code, country".
class User(AbstractUser):
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    

    def __str__(self):
        return self.email


# TODO: Complete custom AccountDetails model.
# Accounts should have a one-to-one relationship with users.
# The account_no field must be unique.
class AccountDetails(models.Model):
    

    def __str__(self):
        return str(self.account_no)


# TODO: Complete custom UserAddress model.
# Addresses should be associated with users in a one-to-one relationship.
class UserAddress(models.Model):


    def __str__(self):
        return self.user.email

src/core/models.py
from django.db import models

# Create your models here.

src/transactions/models.py
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


User = settings.AUTH_USER_MODEL


# TODO: Create Deposit model.
# Deposits should be tied to a user, and should have an amount and timestamp.


# TODO: Create Withdrawal model.
# Withdrawals should be tied to a user, and should have an amount and timestamp.


# TODO: Create Interest model.
# Interests should be tied to a user, and should have an amount and timestamp.

src/accounts/forms.py
from django import forms


# TODO: Create UserRegistrationForm.


# TODO: Create AccountDetailsForm.


# TODO: Create UserAddressForm.


# TODO: Create UserLoginForm.

src/transactions/forms.py
from django import forms

# TODO: Create DepositForm.


# TODO: Create WithdrawalForm.
# This should raise an error if the user attempts to withdrawal more than their balance.

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth import (
    authenticate,
    login,
    logout,
)
from django.shortcuts import render, redirect

from .forms import (
    UserLoginForm, UserRegistrationForm,
    AccountDetailsForm, UserAddressForm,
)


# TODO: Create the register view.
# Upon successful registration, the user should be redirected home and a success message should be displayed.
# This success message should show the user their new account number, which they will need to login.
def register_view(request):
    

    # TODO: The template expects three forms: user_form, account_form, address_form.
    context = {
        "title": "Create a Bank Account",
        "user_form": None,
        "account_form": None,
        "address_form": None,
    }

    return render(request, "accounts/register_form.html", context)


# TODO: Create the login view.
# Upon successful login, the user should be redirected home and a success message should be displayed.
def login_view(request):

    # TODO: The template expects a form for the user login.
    context = {
        "form": None,
        "title": "Log In",
    }

    return render(request, "accounts/form.html", context)


# TODO: Create the logout view.
# Upon successful logout, the user should be redirected to the home page.

src/core/views.py
from django.db.models import Sum
from django.shortcuts import render

from transactions.models import Deposit, Withdrawal, Interest

def home(request):
    if not request.user.is_authenticated:
        return render(request, "core/index.html", {})
    else:
        user = request.user
        deposit = Deposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        context = {
                    "user": user,
                    "deposit": deposit,
                    "deposit_sum": deposit_sum,
                    "withdrawal": withdrawal,
                    "withdrawal_sum": withdrawal_sum,
                    "interest": interest,
                    "interest_sum": interest_sum,
                  }

        return render(request, "core/transactions.html", context)


def about(request):
    return render(request, "core/about.html", {})

src/transactions/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import DepositForm, WithdrawalForm


# TODO: Create the deposit view.
# Deposits should inaccessible if users are not logged in.
# Successful deposits should redirect to the home page and a success message should be displayed.
def deposit_view(request):

    # TODO: The template expects a form for the deposit.
    context = {
        "title": "Deposit",
        "form": None
    }
    return render(request, "transactions/form.html", context)


# TODO: Create the withdrawal view.
# Withdrawals should inaccessible if users are not logged in.
# Successful withdrawals should redirect to the home page and a success message should be displayed.
def withdrawal_view(request):

    # TODO: The template expects a form for the withdrawal.
    context = {
        "title": "Withdraw",
        "form": None
    }
    return render(request, "transactions/form.html", context)

src/accounts/templates/accounts/form.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    {{ title }} | {{ block.super }}
{% endblock title %}
{% block content %}
    {% include "core/messages.html" %}
    <h2>{{ title }}</h2>
    <hr>
    <form method="post" action="" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input class="btn btn-success" type="submit" value='Submit'>
    </form>
{% endblock content %}

src/accounts/templates/accounts/register_form.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    {{ title }} | {{ block.super }}
{% endblock title %}
{% block content %}
    {% include "core/messages.html" %}
    <h2>{{ title }}</h2>
    <hr>
    <form method="post" action="" enctype='multipart/form-data' class="pb-4">
        {% csrf_token %}
        {{ user_form|crispy }}
        {{ account_form|crispy }}
        {{ address_form|crispy }}
        <br>
        <input class="btn btn-success" type="submit" value='Submit'>
    </form>
{% endblock content %}

src/core/templates/core/about.html
{% extends "core/base.html" %}
{% block title %}
  About | {{ block.super }}
{% endblock title %}
{% block content %}
  <h1>About US</h1>
  <hr />
  <p>
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type
    specimen book. It has survived not only five centuries, but also the leap into
    electronic typesetting, remaining essentially unchanged. It was popularised in
    the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    and more recently with desktop publishing software like Aldus PageMaker
    including versions of Lorem Ipsum. Why do we use it?
  </p>
  <p>
    It is a long established fact that a reader will be distracted by the readable
    content of a page when looking at its layout. The point of using Lorem Ipsum
    is that it has a more-or-less normal distribution of letters, as opposed to
    using 'Content here, content here', making it look like readable English. Many
    desktop publishing packages and web page editors now use Lorem Ipsum as their
    default model text, and a search for 'lorem ipsum' will uncover many web sites
    still in their infancy. Various versions have evolved over the years,
    sometimes by accident, sometimes on purpose (injected humour and the like).
  </p>
  <p>
    The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
    those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
    Malorum" by Cicero are also reproduced in their exact original form,
    accompanied by English versions from the 1914 translation by H. Rackham.
  </p>
{% endblock content %}

src/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100 w-100">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Invest in yourself!">
    <meta name="keywords" content="per scholas, bank">
    <title>
      {% block title %}
        PS Bank
      {% endblock title %}
    </title>
    <link rel="icon"
          type="image/png"
          href="{% static 'img/Per_Scholas_Hat.png' %}">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="h-100 w-100">
    {% include "core/navbar.html" %}
    {% block fixed %}
    {% endblock fixed %}
    <div class="container h-100 py-150">
      {% block content %}
      {% endblock content %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
            integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
            crossorigin="anonymous"></script>
  </body>
</html>

src/core/templates/core/home.html
{% extends "core/base.html" %}
{% block title %}
  {{ block.super }}
{% endblock title %}
{% block content %}
  <div class="container pt-50">
    <div class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">PS Bank</h1>
        <hr>
        <p class="lead text-muted">Made by you, for you.</p>
        <p>
          <a class="btn btn-primary btn-md"
             href="{% url 'accounts:login' %}"
             role="button">Log In</a>
          <a class="btn btn-success btn-md"
             href="{% url 'accounts:register' %}"
             role="button">Create Account</a>
        </p>
      </div>
    </div>
  </div>
{% endblock content %}

src/core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}
{% block fixed %}
  <div class="position-fixed w-100 h-100 top-0 left-0">
    <img style="object-fit: cover"
         height="auto"
         width="auto"
         class="w-100 h-100"
         src="{% static 'img/background.jpg' %}"
         alt="" />
  </div>
  <div class="position-fixed w-100 h-100 top-0 left-0">
    <img style="object-fit: cover"
         height="auto"
         width="auto"
         class="w-100 h-100"
         src="{% static 'img/overlay.png' %}"
         alt="" />
  </div>
{% endblock fixed %}
{% block content %}
  <div class="container h-100 d-flex flex-row justify-content-center">
    <div class="row w-100 align-items-center justify-content-center">
      <div class="col-md-8 text-center col-sm-12">
        <h1>Per Scholas Bank</h1>
        <p class="mb-5">
          Per Scholas helps you invest in yourself!
          <br>
          (Not a real bank.)
        </p>
        {% if not request.user.is_authenticated %}
          <p>
            <a href="{% url 'accounts:login' %}"
               class="btn btn-white btn-outline-white">Log In To Account</a>
          </p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}

src/core/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

src/core/templates/core/navbar.html
<header role="banner">
  <nav class="navbar navbar-expand-md">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">PS Bank</a>
      <button class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbar"
              aria-controls="navbar"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:deposit' %}">Deposit</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About Us</a>
          </li>
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
            <li class="nav-item cta-btn">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item cta-btn">
              <a class="nav-link" href="{% url 'accounts:register' %}">Create Account</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

src/core/templates/core/transactions.html
{% extends "core/base.html" %}
{% block title %}
  Transactions | {{ block.super }}
{% endblock title %}
{% block content %}
  {% include "core/messages.html" %}
  <div class="page-header">
    <h1 class="text-center">
      <b>Banking System</b>
      <br>
      <small>PS Bank</small>
    </h1>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8 text-left">
      <h4>
        <b>Account Name: </b>{{ user.full_name }}
      </h4>
      <h4>
        <b>Date of Birth: </b>{{ user.account.birth_date }}
      </h4>
      <h4>
        <b>Gender: </b>{{ user.account.get_gender_display }}
      </h4>
      <h4>
        <b>Contact No: </b>{{ user.contact_no }}
      </h4>
      <h4>
        <b>Email Address: </b>{{ user.email }}
      </h4>
      <h4>
        <b>Address: </b>{{ user.full_address }}
      </h4>
    </div>
    <div class="col-xs-6 col-md-4 text-left">
      <h4>
        <b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}
      </h4>
      <h4>
        <b>Account No: </b>{{ user.account_no }}
      </h4>
      <br>
      <br>
      <div class="well">
        <h4>
          <b>Account Balance: </b>${{ user.balance }}
        </h4>
        <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
        <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
      </div>
    </div>
  </div>
  <hr>
  <div class="page-header">
    <h2 class="text-center">
      <b>Transaction Details</b>
    </h2>
  </div>
  <h3>Deposit Details</h3>
  <table class="table table-dark table-hover table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Date / Time</th>
        <th>Details</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for obj in deposit %}
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ obj.timestamp }}</td>
          <td>Deposit</td>
          <td>${{ obj.amount }}</td>
        </tr>
      {% endfor %}
      <tr>
        <th class="text-right" scope="row" colspan="3">Total</th>
        <td>${{ deposit_sum }}</td>
      </tr>
    </tbody>
  </table>
  <hr>
  <h3>Withdrawal Details</h3>
  <table class="table table-dark table-hover table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Date / Time</th>
        <th>Details</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for obj in withdrawal %}
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ obj.timestamp }}</td>
          <td>Withdrawal</td>
          <td>${{ obj.amount }}</td>
        </tr>
      {% endfor %}
      <tr>
        <th class="text-right" scope="row" colspan="3">Total</th>
        <td>${{ withdrawal_sum }}</td>
      </tr>
    </tbody>
  </table>
  <hr>
  <h3>Interest Details</h3>
  <table class="table table-dark table-hover table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Date / Time</th>
        <th>Details</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for obj in interest %}
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ obj.timestamp }}</td>
          <td>Interest</td>
          <td>${{ obj.amount }}</td>
        </tr>
      {% endfor %}
      <tr>
        <th class="text-right" scope="row" colspan="3">Total</th>
        <td>${{ interest_sum }}</td>
      </tr>
    </tbody>
  </table>
  <hr>
{% endblock content %}

src/transactions/templates/transactions/form.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    {{ title }} | {{ block.super }}
{% endblock title %}
{% block content %}
    {% include "core/messages.html" %}
    <div class="alert alert-primary" role="alert">Your current account balance is ${{ request.user.balance }}.</div>
    <h2>{{ title }}</h2>
    <hr>
    <form method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input class="btn btn-primary" type="submit" value='{{ title }}'>
    </form>
{% endblock content %}